image: ronalddpinho/cpp-build-base

stages:
  - build

before_script:
  # Install dependencies packages
  - apt-get update -y
  - apt-get install -y doxygen libboost-dev libvsqlitepp-dev
  # Building ParadisEO libs
  - mkdir -p build/paradiseo
  - cmake -B build/paradiseo -DEO_ONLY=ON -DCMAKE_INSTALL_PREFIX=. include/paradiseo-master
  - make -C build/paradiseo

build:
  stage: build
  script:
    - cmake -B build .
    - cmake --build build --config Release
    
