image: ronalddpinho/cpp-build-base

stages:
  - build
  - test

before_script:
  # Install dependencies packages
  - apt-get update -y
  - apt-get install -y wget doxygen unzip libboost-graph-dev libvsqlitepp-dev
  - bash scripts/instd.sh

build:
  stage: build
  script:
    - cmake .
    - make
    - make install

unit-tests:
  stage: test
  script:
    - make test
