image: ronalddpinho/cpp-build-base

stages:
  - build

before_script:
  # Install dependencies packages
  - apt-get update -y
  - apt-get install -y doxygen libboost-dev libvsqlitepp-dev
  - bash install-paradiseo.sh

build:
  stage: build
  script:
    - cmake .
    - make
    
