# Operadores de Crossover:
# 0 - Crossover Uniforme
# 1 - Um-Ponto de Corte
# N - N-Pontos de Corte (com N >= 2)
crossover: [ 0, 1, 2, 4, 8 ]

# Taxas de Cruzamento (de 0.0 a 1.0)
xrate: 1.0

# Taxa de mutação (de 0.0 a 1.0)
mrate: 0.005

# Tamanho da população (no. inteiro)
popsize: 50

# Número maximo de verificacoes (no. inteiro)
stop: 10000

# Tamanho do torneio (no. inteiro)
ring: 4

# arquivos de instâncias teste (string - caminho para arquivo)
infile:
  - /data/mkp/mknapcb31.txt
  - /data/mkp/mknapcb61.txt
  - /data/mkp/mknapcb91.txt

# Nome do arquivo de banco de dados para salvar os resultados colhidos
# (string - caminho para um arquivo)
db: "/db/resultados_1.sqlite"
