run:
  # Sigle do problema para fazer as execuções
  # as opções são
  # --- scp: cobertura de conjuntos
  # --- mkp: mochila multidimensional
  # --- mcp: clique máximo
  # --- stp: árvore de Steiner
  problem: scp
  
  # Caminho para o arquivo de instância do problema
  instance: instances/scp/scp41.txt

  # Definição dos parâmetros de execuções
  args:
    # Taxas de cruzamento: 60%, 80% e 100%
    crossover_rate: 1.0

    # Taxa de mutação de 4%
    mutation_rate: 0.04

    # Crossover: (0) Uniforme, (1) Um-ponto e (4) 4-pontos ...
    crossover: [ 0, 1, 2, 16, 120 ]

    # Tamanho de população
    population: 50

    # Número de gerações
    epochs: 100

