# Operadores de Crossover:
# 0 - Crossover Uniforme
# 1 - Um-Ponto de Corte
# N - N-Pontos de Corte (com N >= 2)
crossover: [ 0, 1, 2, 4 ]

# Taxas de Cruzamento (de 0.0 a 1.0)
xrate: 1.0

# Taxa de mutação (de 0.0 a 1.0)
mrate: 0.002

# Tamanho da população (no. inteiro)
popsize: 100

# Número de gerações (no. inteiro)
epochs: 200

# Tamanho do torneio (no. inteiro)
ring: 4

# arquivos de instâncias teste (string - caminho para arquivo)
infile:
  # - /data/stp/steinc4.txt  # [feito]
  # - /data/stp/steinc5.txt  # [feito]
  # - /data/stp/steind3.txt  # [feito]
  # - /data/stp/steind4.txt  # [feito]
  # - /data/stp/steind5.txt  # [feito]
  # - /data/stp/steine3.txt  # [feito]
  # - /data/stp/steine4.txt  # [0, 1, 2, 4,...]
  - /data/stp/steine5.txt  # [...]


# Nome do arquivo de banco de dados para salvar os resultados colhidos
# (string - caminho para um arquivo)
db: "/db/ExperimentosSTP.db3"
