run:
  program: bin/ga4scp 
  # Executável do problema de cobertura de conjuntos

  # Definição dos parâmetros de execuções
  args:
    # Taxas de cruzamento: 60%, 80% e 100%
    crossover_rate: [ 0.5, 1.0 ]

    # Taxa de mutação de 4%
    mutation_rate: 0.04

    # Crossover: (0) Uniforme, (1) Um-ponto e (4) 4-pontos
    crossover:
      - 0
      - 1
      - 2
      - 10

    # Tamanho de população
    population: 200

    # Número de gerações
    epochs: 150

    # Arquivo de instância do problem
    instance: /home/ronaldd/Projects/scpxx/instances/scp41.txt

