name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: bash build.sh
    - name: Generating Makefiles with CMake
      run: mkdir build && cd build && cmake ..
    - name: Make
      run: cd build && make

  scripts:
    runs-on: ubunut-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: chmod +x install_dependencies.sh && ./install_dependencies.sh
    - name: Build project
      run: chmod +x build.sh && ./build.sh
    