name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  prebuild:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: chmod +x install_dependencies.sh && ./install_dependencies.sh


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: bash build.sh
    - name: Generating Makefiles with CMake
      run: mkdir build && cd build && cmake ..
    - name: Make
      run: cd build && make
    