name: CMake Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Dependencies
      run: |
        sudo apt-get install -y
        sudo apt-get install -y cmake wget unzip doxygen
        sudo apt-get install -y libvsqlitepp-dev libboost-graph-dev
    - name: Building ParadisEO
      run: |
        mkdir -p build/paradiseo
        cmake -B build/paradiseo -DEO_ONLY=ON -DCMAKE_INSTALL_PREFIX=. include/paradiseo-master
        make -C build/paradiseo
    - name: Building the project
      run: |
        cmake -B build .
        make -C build
